### ISSUE TITLE
Switch to MutationObserver

### ISSUE THREAD

**Issue by zerebos** [JadeMin/BetterDiscordPlugins#2]
Interval polling (https://github.com/JadeMin/BetterDiscordAddons/blob/main/Plugins/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js#L34) is not good for end-users. I highly recommend switching to using some form of MutationObserver, please reach out here or on Discord if you need assistance.

**Comment by JadeMin** [comment]
I was expecting this code to have a bad performance impact for the users. so i'll deal with the performance issues by adding event listeners and so on.
Thanks for the advice!

**Comment by KlartNET** [comment]
fixed
https://github.com/JadeMin/BetterDiscordPlugins/blob/main/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js
