### ISSUE TITLE
[YTEmbedSuggestion] Developer Logger setting does nothing. 

### ISSUE THREAD

**Issue by Strencher** [JadeMin/BetterDiscordPlugins#3]
Setting to disable console debugging doesn't actually do anything. (Defined at [YTEmbedSuggestion.plugin.js#L27-L33](https://github.com/JadeMin/BetterDiscordPlugins/blob/main/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js#L27-L33)).
The setting isn't even available since a `getSettingsPanel() {}` method in your plugin class doesn't exists. I recommend you to read the docs of [BetterDiscord/BetterDiscord](https://github.com/BetterDiscord/BetterDiscord/wiki/Creating-Plugins#getsettingspanel) an´d tell BetterDiscord to add a settings button. May also read the docs of [ZeresPluginLibrary](https://rauenzi.github.io/BDPluginLibrary/docs/)

<hr/>

Also, i recommend you to simply just `return` at [YTEmbedSuggestion.plugin.js#L86](https://github.com/JadeMin/BetterDiscordPlugins/blob/main/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js#L86) since you basically do nothing when it isn't an `HTMLIframeElement`.

**Comment by KlartNET** [comment]
The developer logger option is deprecated yet.
https://github.com/JadeMin/BetterDiscordPlugins/blob/8bde7b8d64ce1593df7dd4e017f72bf7fd0b5af9/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js#L27-L33

https://github.com/JadeMin/BetterDiscordPlugins/blob/2593c7721584109d82d9e0b5b70cc2a2879fd905/YTEmbedSuggestion/YTEmbedSuggestion.plugin.js#L85-L87
